
AHScannerDB = {
	["Bronzebeard - Warcraft Reborn"] = {
		["Copper Ore"] = {
			["items"] = {
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [1]
				{
					["buyoutUnit"] = 39800,
					["seller"] = "Moonluna",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 39800,
					["name"] = "Copper Ore",
					["minBid"] = 37700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 37700,
					["quality"] = 1,
				}, -- [2]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [3]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [4]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [5]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [6]
				{
					["buyoutUnit"] = 1556,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 31120,
					["name"] = "Copper Ore",
					["minBid"] = 31120,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1556,
					["quality"] = 1,
				}, -- [7]
				{
					["buyoutUnit"] = 1550,
					["seller"] = "Shikifujin",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1550,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [8]
				{
					["buyoutUnit"] = 2200,
					["seller"] = "Kawazaki",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 22000,
					["name"] = "Copper Ore",
					["minBid"] = 10000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1000,
					["quality"] = 1,
				}, -- [9]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [10]
				{
					["buyoutUnit"] = 1562,
					["seller"] = "Qvothe",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1562,
					["name"] = "Copper Ore",
					["minBid"] = 1483,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1483,
					["quality"] = 1,
				}, -- [11]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [12]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [13]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [14]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [15]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [16]
				{
					["buyoutUnit"] = 1600,
					["seller"] = "Icedragon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32000,
					["name"] = "Copper Ore",
					["minBid"] = 31900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1595,
					["quality"] = 1,
				}, -- [17]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [18]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [19]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [20]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [21]
				{
					["buyoutUnit"] = 1640,
					["seller"] = "Ladutta",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32800,
					["name"] = "Copper Ore",
					["minBid"] = 31100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1555,
					["quality"] = 1,
				}, -- [22]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [23]
				{
					["buyoutUnit"] = 1515,
					["seller"] = "Nazus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30300,
					["name"] = "Copper Ore",
					["minBid"] = 28900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1445,
					["quality"] = 1,
				}, -- [24]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [25]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [26]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [27]
				{
					["buyoutUnit"] = 1600,
					["seller"] = "Icedragon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32000,
					["name"] = "Copper Ore",
					["minBid"] = 31900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1595,
					["quality"] = 1,
				}, -- [28]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [29]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [30]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 12,
					["buyout"] = 59988,
					["name"] = "Copper Ore",
					["minBid"] = 59988,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [31]
				{
					["buyoutUnit"] = 1519,
					["seller"] = "Megarelax",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1519,
					["name"] = "Copper Ore",
					["minBid"] = 1502,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1502,
					["quality"] = 1,
				}, -- [32]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [33]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [34]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [35]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [36]
				{
					["buyoutUnit"] = 1545,
					["seller"] = "Lovegolang",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1545,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [37]
				{
					["buyoutUnit"] = 23020,
					["seller"] = "Jellybear",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 460400,
					["name"] = "Copper Ore",
					["minBid"] = 441600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 22080,
					["quality"] = 1,
				}, -- [38]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [39]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [40]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [41]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [42]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [43]
				{
					["buyoutUnit"] = 40000,
					["seller"] = "Xandil",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 800000,
					["name"] = "Copper Ore",
					["minBid"] = 402000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 20100,
					["quality"] = 1,
				}, -- [44]
				{
					["buyoutUnit"] = 40000,
					["seller"] = "Xandil",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 800000,
					["name"] = "Copper Ore",
					["minBid"] = 402000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 20100,
					["quality"] = 1,
				}, -- [45]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [46]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [47]
				{
					["buyoutUnit"] = 23020,
					["seller"] = "Jellybear",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 460400,
					["name"] = "Copper Ore",
					["minBid"] = 441600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 22080,
					["quality"] = 1,
				}, -- [48]
				{
					["buyoutUnit"] = 23020,
					["seller"] = "Jellybear",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 460400,
					["name"] = "Copper Ore",
					["minBid"] = 441600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 22080,
					["quality"] = 1,
				}, -- [49]
				{
					["buyoutUnit"] = 1556,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 31120,
					["name"] = "Copper Ore",
					["minBid"] = 31120,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1556,
					["quality"] = 1,
				}, -- [50]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [51]
				{
					["buyoutUnit"] = 1640,
					["seller"] = "Lianshou",
					["bidAmount"] = 0,
					["count"] = 6,
					["buyout"] = 9840,
					["name"] = "Copper Ore",
					["minBid"] = 9330,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1555,
					["quality"] = 1,
				}, -- [52]
				{
					["buyoutUnit"] = 1515,
					["seller"] = "Nazus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30300,
					["name"] = "Copper Ore",
					["minBid"] = 28900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1445,
					["quality"] = 1,
				}, -- [53]
				{
					["buyoutUnit"] = 1544,
					["seller"] = "Catah",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1544,
					["name"] = "Copper Ore",
					["minBid"] = 1544,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1544,
					["quality"] = 1,
				}, -- [54]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [55]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [56]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [57]
				{
					["buyoutUnit"] = 1556,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 31120,
					["name"] = "Copper Ore",
					["minBid"] = 31120,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1556,
					["quality"] = 1,
				}, -- [58]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [59]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [60]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [61]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [62]
				{
					["buyoutUnit"] = 1179,
					["seller"] = "Galaktix",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1179,
					["name"] = "Copper Ore",
					["minBid"] = 1179,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1179,
					["quality"] = 1,
				}, -- [63]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [64]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [65]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [66]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [67]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anqs",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [68]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anqs",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [69]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [70]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [71]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anqs",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [72]
				{
					["buyoutUnit"] = 2200,
					["seller"] = "Kawazaki",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 22000,
					["name"] = "Copper Ore",
					["minBid"] = 10000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1000,
					["quality"] = 1,
				}, -- [73]
				{
					["buyoutUnit"] = 1542,
					["seller"] = "Mooriel",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1542,
					["name"] = "Copper Ore",
					["minBid"] = 1463,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1463,
					["quality"] = 1,
				}, -- [74]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anqs",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [75]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [76]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [77]
				{
					["buyoutUnit"] = 1940,
					["seller"] = "Sokofreta",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 38800,
					["name"] = "Copper Ore",
					["minBid"] = 36800,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1840,
					["quality"] = 1,
				}, -- [78]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [79]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [80]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [81]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [82]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [83]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [84]
				{
					["buyoutUnit"] = 1760,
					["seller"] = "Hebanks",
					["bidAmount"] = 0,
					["count"] = 8,
					["buyout"] = 14080,
					["name"] = "Copper Ore",
					["minBid"] = 14080,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1760,
					["quality"] = 1,
				}, -- [85]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [86]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [87]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [88]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [89]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [90]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [91]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [92]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [93]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [94]
				{
					["buyoutUnit"] = 1698,
					["seller"] = "Zeronica",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3396,
					["name"] = "Copper Ore",
					["minBid"] = 3226,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1613,
					["quality"] = 1,
				}, -- [95]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [96]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [97]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [98]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [99]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [100]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [101]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [102]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [103]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [104]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [105]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [106]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [107]
				{
					["buyoutUnit"] = 81818,
					["seller"] = "Snaffel",
					["bidAmount"] = 0,
					["count"] = 11,
					["buyout"] = 900000,
					["name"] = "Copper Ore",
					["minBid"] = 700100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 63645,
					["quality"] = 1,
				}, -- [108]
				{
					["buyoutUnit"] = 1611,
					["seller"] = "Korggoth",
					["bidAmount"] = 0,
					["count"] = 18,
					["buyout"] = 29000,
					["name"] = "Copper Ore",
					["minBid"] = 25000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1388,
					["quality"] = 1,
				}, -- [109]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [110]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [111]
				{
					["buyoutUnit"] = 1760,
					["seller"] = "Hebanks",
					["bidAmount"] = 0,
					["count"] = 17,
					["buyout"] = 29920,
					["name"] = "Copper Ore",
					["minBid"] = 29920,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1760,
					["quality"] = 1,
				}, -- [112]
				{
					["buyoutUnit"] = 985,
					["seller"] = "Dhalinhar",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 9850,
					["name"] = "Copper Ore",
					["minBid"] = 9300,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 930,
					["quality"] = 1,
				}, -- [113]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [114]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [115]
				{
					["buyoutUnit"] = 1544,
					["seller"] = "Catah",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1544,
					["name"] = "Copper Ore",
					["minBid"] = 1544,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1544,
					["quality"] = 1,
				}, -- [116]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [117]
				{
					["buyoutUnit"] = 1200,
					["seller"] = "Ramekiah",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1200,
					["name"] = "Copper Ore",
					["minBid"] = 1100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1100,
					["quality"] = 1,
				}, -- [118]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [119]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [120]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [121]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [122]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [123]
				{
					["buyoutUnit"] = 1549,
					["seller"] = "Catah",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1549,
					["name"] = "Copper Ore",
					["minBid"] = 1549,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1549,
					["quality"] = 1,
				}, -- [124]
				{
					["buyoutUnit"] = 1646,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32920,
					["name"] = "Copper Ore",
					["minBid"] = 32920,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1646,
					["quality"] = 1,
				}, -- [125]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [126]
				{
					["buyoutUnit"] = 1640,
					["seller"] = "Ladutta",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32800,
					["name"] = "Copper Ore",
					["minBid"] = 31100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1555,
					["quality"] = 1,
				}, -- [127]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [128]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Erdeksw",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [129]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [130]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [131]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [132]
				{
					["buyoutUnit"] = 1200,
					["seller"] = "Ramekiah",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1200,
					["name"] = "Copper Ore",
					["minBid"] = 1100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1100,
					["quality"] = 1,
				}, -- [133]
				{
					["buyoutUnit"] = 1760,
					["seller"] = "Crozorg",
					["bidAmount"] = 0,
					["count"] = 13,
					["buyout"] = 22880,
					["name"] = "Copper Ore",
					["minBid"] = 22880,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1760,
					["quality"] = 1,
				}, -- [134]
				{
					["buyoutUnit"] = 1200,
					["seller"] = "Ramekiah",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1200,
					["name"] = "Copper Ore",
					["minBid"] = 1100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1100,
					["quality"] = 1,
				}, -- [135]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [136]
				{
					["buyoutUnit"] = 23020,
					["seller"] = "Jellybear",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 460400,
					["name"] = "Copper Ore",
					["minBid"] = 441600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 22080,
					["quality"] = 1,
				}, -- [137]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [138]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [139]
				{
					["buyoutUnit"] = 1600,
					["seller"] = "Icedragon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32000,
					["name"] = "Copper Ore",
					["minBid"] = 31900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1595,
					["quality"] = 1,
				}, -- [140]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [141]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [142]
				{
					["buyoutUnit"] = 1640,
					["seller"] = "Ladutta",
					["bidAmount"] = 0,
					["count"] = 13,
					["buyout"] = 21320,
					["name"] = "Copper Ore",
					["minBid"] = 20215,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1555,
					["quality"] = 1,
				}, -- [143]
				{
					["buyoutUnit"] = 1190,
					["seller"] = "Galenia",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 2380,
					["name"] = "Copper Ore",
					["minBid"] = 2250,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1125,
					["quality"] = 1,
				}, -- [144]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [145]
				{
					["buyoutUnit"] = 1646,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 12,
					["buyout"] = 19752,
					["name"] = "Copper Ore",
					["minBid"] = 19752,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1646,
					["quality"] = 1,
				}, -- [146]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [147]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [148]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [149]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [150]
				{
					["buyoutUnit"] = 1556,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 31120,
					["name"] = "Copper Ore",
					["minBid"] = 31120,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1556,
					["quality"] = 1,
				}, -- [151]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [152]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [153]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Fallenlord",
					["bidAmount"] = 900,
					["count"] = 9,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 45,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [154]
				{
					["buyoutUnit"] = 990,
					["seller"] = "Mopke",
					["bidAmount"] = 0,
					["count"] = 15,
					["buyout"] = 14850,
					["name"] = "Copper Ore",
					["minBid"] = 14025,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 935,
					["quality"] = 1,
				}, -- [155]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [156]
				{
					["buyoutUnit"] = 1941,
					["seller"] = "Sokofreta",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 38820,
					["name"] = "Copper Ore",
					["minBid"] = 36800,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1840,
					["quality"] = 1,
				}, -- [157]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [158]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [159]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [160]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [161]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [162]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [163]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [164]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [165]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [166]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [167]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [168]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [169]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [170]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [171]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [172]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [173]
				{
					["buyoutUnit"] = 2200,
					["seller"] = "Kawazaki",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 22000,
					["name"] = "Copper Ore",
					["minBid"] = 10000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1000,
					["quality"] = 1,
				}, -- [174]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [175]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [176]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [177]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [178]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [179]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [180]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [181]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [182]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [183]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [184]
				{
					["buyoutUnit"] = 1180,
					["seller"] = "Vladdee",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 2360,
					["name"] = "Copper Ore",
					["minBid"] = 2235,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1117,
					["quality"] = 1,
				}, -- [185]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [186]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [187]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [188]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [189]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [190]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [191]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [192]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [193]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [194]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [195]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [196]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [197]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [198]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [199]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 5,
					["buyout"] = 24995,
					["name"] = "Copper Ore",
					["minBid"] = 24995,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [200]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [201]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [202]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [203]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [204]
				{
					["buyoutUnit"] = 1760,
					["seller"] = "Palaremziye",
					["bidAmount"] = 0,
					["count"] = 11,
					["buyout"] = 19360,
					["name"] = "Copper Ore",
					["minBid"] = 19360,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1760,
					["quality"] = 1,
				}, -- [205]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [206]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [207]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [208]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [209]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [210]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [211]
				{
					["buyoutUnit"] = 1200,
					["seller"] = "Ramekiah",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1200,
					["name"] = "Copper Ore",
					["minBid"] = 1100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1100,
					["quality"] = 1,
				}, -- [212]
				{
					["buyoutUnit"] = 2200,
					["seller"] = "Kawazaki",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 22000,
					["name"] = "Copper Ore",
					["minBid"] = 10000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1000,
					["quality"] = 1,
				}, -- [213]
				{
					["buyoutUnit"] = 1555,
					["seller"] = "Helgyd",
					["bidAmount"] = 0,
					["count"] = 15,
					["buyout"] = 23325,
					["name"] = "Copper Ore",
					["minBid"] = 22000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1466,
					["quality"] = 1,
				}, -- [214]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [215]
				{
					["buyoutUnit"] = 1544,
					["seller"] = "Catah",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1544,
					["name"] = "Copper Ore",
					["minBid"] = 1544,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1544,
					["quality"] = 1,
				}, -- [216]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [217]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [218]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [219]
				{
					["buyoutUnit"] = 1519,
					["seller"] = "Megarelax",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1519,
					["name"] = "Copper Ore",
					["minBid"] = 1502,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1502,
					["quality"] = 1,
				}, -- [220]
				{
					["buyoutUnit"] = 1646,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32920,
					["name"] = "Copper Ore",
					["minBid"] = 32920,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1646,
					["quality"] = 1,
				}, -- [221]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [222]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [223]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [224]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [225]
				{
					["buyoutUnit"] = 1611,
					["seller"] = "Mykuhl",
					["bidAmount"] = 0,
					["count"] = 19,
					["buyout"] = 30609,
					["name"] = "Copper Ore",
					["minBid"] = 29078,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1530,
					["quality"] = 1,
				}, -- [226]
				{
					["buyoutUnit"] = 1000,
					["seller"] = "Nastypuss",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 900,
					["quality"] = 1,
				}, -- [227]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [228]
				{
					["buyoutUnit"] = 2200,
					["seller"] = "Kawazaki",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 22000,
					["name"] = "Copper Ore",
					["minBid"] = 10000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1000,
					["quality"] = 1,
				}, -- [229]
				{
					["buyoutUnit"] = 1519,
					["seller"] = "Megarelax",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1519,
					["name"] = "Copper Ore",
					["minBid"] = 1502,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1502,
					["quality"] = 1,
				}, -- [230]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 12,
					["buyout"] = 59988,
					["name"] = "Copper Ore",
					["minBid"] = 59988,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [231]
				{
					["buyoutUnit"] = 2200,
					["seller"] = "Kawazaki",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 22000,
					["name"] = "Copper Ore",
					["minBid"] = 10000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1000,
					["quality"] = 1,
				}, -- [232]
				{
					["buyoutUnit"] = 2200,
					["seller"] = "Kawazaki",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 22000,
					["name"] = "Copper Ore",
					["minBid"] = 10000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1000,
					["quality"] = 1,
				}, -- [233]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [234]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [235]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [236]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Noxrebirth",
					["bidAmount"] = 0,
					["count"] = 9,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 18000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2000,
					["quality"] = 1,
				}, -- [237]
				{
					["buyoutUnit"] = 2500,
					["seller"] = "Ohotnik",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 50000,
					["name"] = "Copper Ore",
					["minBid"] = 40100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2005,
					["quality"] = 1,
				}, -- [238]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [239]
				{
					["buyoutUnit"] = 1519,
					["seller"] = "Megarelax",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1519,
					["name"] = "Copper Ore",
					["minBid"] = 1502,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1502,
					["quality"] = 1,
				}, -- [240]
				{
					["buyoutUnit"] = 994,
					["seller"] = "Jelnary",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 994,
					["name"] = "Copper Ore",
					["minBid"] = 942,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 942,
					["quality"] = 1,
				}, -- [241]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Furrythead",
					["bidAmount"] = 0,
					["count"] = 12,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 1200,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [242]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [243]
				{
					["buyoutUnit"] = 1645,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32900,
					["name"] = "Copper Ore",
					["minBid"] = 31150,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1557,
					["quality"] = 1,
				}, -- [244]
			},
		},
	},
}