
AHScannerDB = {
	["Bronzebeard - Warcraft Reborn"] = {
		["Copper Ore"] = {
			["items"] = {
				{
					["buyoutUnit"] = 0,
					["seller"] = "Canderus",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [1]
				{
					["buyoutUnit"] = 4000,
					["seller"] = "Klita",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 8000,
					["name"] = "Copper Ore",
					["minBid"] = 8000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4000,
					["quality"] = 1,
				}, -- [2]
				{
					["buyoutUnit"] = 1389,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 13890,
					["name"] = "Copper Ore",
					["minBid"] = 13180,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1318,
					["quality"] = 1,
				}, -- [3]
				{
					["buyoutUnit"] = 1499,
					["seller"] = "Bankerbob",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 14990,
					["name"] = "Copper Ore",
					["minBid"] = 14990,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1499,
					["quality"] = 1,
				}, -- [4]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [5]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [6]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [7]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [8]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [9]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [10]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [11]
				{
					["buyoutUnit"] = 1442,
					["seller"] = "Hacon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 28850,
					["name"] = "Copper Ore",
					["minBid"] = 28850,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1442,
					["quality"] = 1,
				}, -- [12]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [13]
				{
					["buyoutUnit"] = 1470,
					["seller"] = "Meepa",
					["bidAmount"] = 0,
					["count"] = 5,
					["buyout"] = 7350,
					["name"] = "Copper Ore",
					["minBid"] = 6900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1380,
					["quality"] = 1,
				}, -- [14]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [15]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [16]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [17]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [18]
				{
					["buyoutUnit"] = 1395,
					["seller"] = "Mythokis",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 13950,
					["name"] = "Copper Ore",
					["minBid"] = 13200,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1320,
					["quality"] = 1,
				}, -- [19]
				{
					["buyoutUnit"] = 1646,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32920,
					["name"] = "Copper Ore",
					["minBid"] = 32920,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1646,
					["quality"] = 1,
				}, -- [20]
				{
					["buyoutUnit"] = 1515,
					["seller"] = "Cjlecap",
					["bidAmount"] = 0,
					["count"] = 8,
					["buyout"] = 12120,
					["name"] = "Copper Ore",
					["minBid"] = 11480,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1435,
					["quality"] = 1,
				}, -- [21]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Machor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [22]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [23]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [24]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [25]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [26]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [27]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [28]
				{
					["buyoutUnit"] = 1940,
					["seller"] = "Sokofreta",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 38800,
					["name"] = "Copper Ore",
					["minBid"] = 36800,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1840,
					["quality"] = 1,
				}, -- [29]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [30]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [31]
				{
					["buyoutUnit"] = 1442,
					["seller"] = "Hacon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 28850,
					["name"] = "Copper Ore",
					["minBid"] = 28850,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1442,
					["quality"] = 1,
				}, -- [32]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Durzeer",
					["bidAmount"] = 0,
					["count"] = 18,
					["buyout"] = 27000,
					["name"] = "Copper Ore",
					["minBid"] = 5000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 277,
					["quality"] = 1,
				}, -- [33]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [34]
				{
					["buyoutUnit"] = 1485,
					["seller"] = "Melificus",
					["bidAmount"] = 0,
					["count"] = 4,
					["buyout"] = 5940,
					["name"] = "Copper Ore",
					["minBid"] = 5620,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1405,
					["quality"] = 1,
				}, -- [35]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [36]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [37]
				{
					["buyoutUnit"] = 39800,
					["seller"] = "Moonluna",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 39800,
					["name"] = "Copper Ore",
					["minBid"] = 37700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 37700,
					["quality"] = 1,
				}, -- [38]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [39]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [40]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [41]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [42]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Machor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [43]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [44]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [45]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [46]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [47]
				{
					["buyoutUnit"] = 30000,
					["seller"] = "Sostenadaura",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 600000,
					["name"] = "Copper Ore",
					["minBid"] = 580000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 29000,
					["quality"] = 1,
				}, -- [48]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [49]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [50]
				{
					["buyoutUnit"] = 1760,
					["seller"] = "Palaremziye",
					["bidAmount"] = 0,
					["count"] = 11,
					["buyout"] = 19360,
					["name"] = "Copper Ore",
					["minBid"] = 19360,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1760,
					["quality"] = 1,
				}, -- [51]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [52]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [53]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [54]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [55]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [56]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [57]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [58]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [59]
				{
					["buyoutUnit"] = 1537,
					["seller"] = "Gallstaff",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30750,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [60]
				{
					["buyoutUnit"] = 1537,
					["seller"] = "Gallstaff",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30750,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [61]
				{
					["buyoutUnit"] = 1640,
					["seller"] = "Ladutta",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32800,
					["name"] = "Copper Ore",
					["minBid"] = 31100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1555,
					["quality"] = 1,
				}, -- [62]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Uggadugga",
					["bidAmount"] = 100,
					["count"] = 2,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 50,
					["quality"] = 1,
				}, -- [63]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [64]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [65]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [66]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [67]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [68]
				{
					["buyoutUnit"] = 1611,
					["seller"] = "Mykuhl",
					["bidAmount"] = 0,
					["count"] = 19,
					["buyout"] = 30609,
					["name"] = "Copper Ore",
					["minBid"] = 29078,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1530,
					["quality"] = 1,
				}, -- [69]
				{
					["buyoutUnit"] = 1537,
					["seller"] = "Gallstaff",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30750,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [70]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [71]
				{
					["buyoutUnit"] = 23020,
					["seller"] = "Jellybear",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 460400,
					["name"] = "Copper Ore",
					["minBid"] = 441600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 22080,
					["quality"] = 1,
				}, -- [72]
				{
					["buyoutUnit"] = 1389,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 13890,
					["name"] = "Copper Ore",
					["minBid"] = 13180,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1318,
					["quality"] = 1,
				}, -- [73]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [74]
				{
					["buyoutUnit"] = 1750,
					["seller"] = "Icedragon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 35000,
					["name"] = "Copper Ore",
					["minBid"] = 34900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1745,
					["quality"] = 1,
				}, -- [75]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [76]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [77]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [78]
				{
					["buyoutUnit"] = 1389,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 13890,
					["name"] = "Copper Ore",
					["minBid"] = 13180,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1318,
					["quality"] = 1,
				}, -- [79]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [80]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [81]
				{
					["buyoutUnit"] = 1640,
					["seller"] = "Ladutta",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32800,
					["name"] = "Copper Ore",
					["minBid"] = 31100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1555,
					["quality"] = 1,
				}, -- [82]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [83]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anqs",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [84]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [85]
				{
					["buyoutUnit"] = 1760,
					["seller"] = "Crozorg",
					["bidAmount"] = 0,
					["count"] = 13,
					["buyout"] = 22880,
					["name"] = "Copper Ore",
					["minBid"] = 22880,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1760,
					["quality"] = 1,
				}, -- [86]
				{
					["buyoutUnit"] = 10000,
					["seller"] = "Sostenadaura",
					["bidAmount"] = 0,
					["count"] = 9,
					["buyout"] = 90000,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [87]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [88]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [89]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [90]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [91]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [92]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [93]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [94]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [95]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [96]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Fallenlord",
					["bidAmount"] = 1093,
					["count"] = 9,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 900,
					["minIncrement"] = 54,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [97]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [98]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [99]
				{
					["buyoutUnit"] = 1515,
					["seller"] = "Firedragon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30300,
					["name"] = "Copper Ore",
					["minBid"] = 30100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1505,
					["quality"] = 1,
				}, -- [100]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [101]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [102]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [103]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Noxrebirth",
					["bidAmount"] = 0,
					["count"] = 9,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 18000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2000,
					["quality"] = 1,
				}, -- [104]
				{
					["buyoutUnit"] = 1442,
					["seller"] = "Hacon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 28850,
					["name"] = "Copper Ore",
					["minBid"] = 28850,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1442,
					["quality"] = 1,
				}, -- [105]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [106]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [107]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [108]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [109]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [110]
				{
					["buyoutUnit"] = 1510,
					["seller"] = "Chronial",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30200,
					["name"] = "Copper Ore",
					["minBid"] = 28600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1430,
					["quality"] = 1,
				}, -- [111]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [112]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [113]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [114]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [115]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [116]
				{
					["buyoutUnit"] = 1698,
					["seller"] = "Zeronica",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3396,
					["name"] = "Copper Ore",
					["minBid"] = 3226,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1613,
					["quality"] = 1,
				}, -- [117]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [118]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [119]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [120]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [121]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [122]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Sheara",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 40000,
					["name"] = "Copper Ore",
					["minBid"] = 37900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1895,
					["quality"] = 1,
				}, -- [123]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [124]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [125]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [126]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [127]
				{
					["buyoutUnit"] = 1442,
					["seller"] = "Hacon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 28850,
					["name"] = "Copper Ore",
					["minBid"] = 28850,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1442,
					["quality"] = 1,
				}, -- [128]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [129]
				{
					["buyoutUnit"] = 13000,
					["seller"] = "Netty",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 260000,
					["name"] = "Copper Ore",
					["minBid"] = 220000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 11000,
					["quality"] = 1,
				}, -- [130]
				{
					["buyoutUnit"] = 1556,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 31120,
					["name"] = "Copper Ore",
					["minBid"] = 31120,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1556,
					["quality"] = 1,
				}, -- [131]
				{
					["buyoutUnit"] = 1536,
					["seller"] = "Fessacchiona",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30720,
					["name"] = "Copper Ore",
					["minBid"] = 30720,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1536,
					["quality"] = 1,
				}, -- [132]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [133]
				{
					["buyoutUnit"] = 1515,
					["seller"] = "Pisha",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1515,
					["name"] = "Copper Ore",
					["minBid"] = 1435,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1435,
					["quality"] = 1,
				}, -- [134]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [135]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [136]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [137]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [138]
				{
					["buyoutUnit"] = 1646,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 12,
					["buyout"] = 19752,
					["name"] = "Copper Ore",
					["minBid"] = 19752,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1646,
					["quality"] = 1,
				}, -- [139]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [140]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [141]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [142]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [143]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [144]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [145]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [146]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [147]
				{
					["buyoutUnit"] = 1465,
					["seller"] = "Padrekarras",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1465,
					["name"] = "Copper Ore",
					["minBid"] = 1300,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1300,
					["quality"] = 1,
				}, -- [148]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Machor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 22000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1100,
					["quality"] = 1,
				}, -- [149]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [150]
				{
					["buyoutUnit"] = 1542,
					["seller"] = "Mooriel",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1542,
					["name"] = "Copper Ore",
					["minBid"] = 1463,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1463,
					["quality"] = 1,
				}, -- [151]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [152]
				{
					["buyoutUnit"] = 1536,
					["seller"] = "Fessacchiona",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30720,
					["name"] = "Copper Ore",
					["minBid"] = 30720,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1536,
					["quality"] = 1,
				}, -- [153]
				{
					["buyoutUnit"] = 1536,
					["seller"] = "Fessacchiona",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30720,
					["name"] = "Copper Ore",
					["minBid"] = 30720,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1536,
					["quality"] = 1,
				}, -- [154]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [155]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [156]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [157]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [158]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [159]
				{
					["buyoutUnit"] = 1941,
					["seller"] = "Sokofreta",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 38820,
					["name"] = "Copper Ore",
					["minBid"] = 36800,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1840,
					["quality"] = 1,
				}, -- [160]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [161]
				{
					["buyoutUnit"] = 1510,
					["seller"] = "Chronial",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30200,
					["name"] = "Copper Ore",
					["minBid"] = 28600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1430,
					["quality"] = 1,
				}, -- [162]
				{
					["buyoutUnit"] = 1510,
					["seller"] = "Chronial",
					["bidAmount"] = 0,
					["count"] = 3,
					["buyout"] = 4530,
					["name"] = "Copper Ore",
					["minBid"] = 4290,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1430,
					["quality"] = 1,
				}, -- [163]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [164]
				{
					["buyoutUnit"] = 1389,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 13890,
					["name"] = "Copper Ore",
					["minBid"] = 13180,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1318,
					["quality"] = 1,
				}, -- [165]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [166]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [167]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 11,
					["buyout"] = 54989,
					["name"] = "Copper Ore",
					["minBid"] = 54989,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [168]
				{
					["buyoutUnit"] = 1537,
					["seller"] = "Gallstaff",
					["bidAmount"] = 0,
					["count"] = 9,
					["buyout"] = 13833,
					["name"] = "Copper Ore",
					["minBid"] = 13095,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [169]
				{
					["buyoutUnit"] = 1495,
					["seller"] = "Belholyone",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 29900,
					["name"] = "Copper Ore",
					["minBid"] = 29899,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1494,
					["quality"] = 1,
				}, -- [170]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [171]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [172]
				{
					["buyoutUnit"] = 1536,
					["seller"] = "Fessacchiona",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30720,
					["name"] = "Copper Ore",
					["minBid"] = 30720,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1536,
					["quality"] = 1,
				}, -- [173]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [174]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [175]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [176]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [177]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [178]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [179]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [180]
				{
					["buyoutUnit"] = 1556,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 31120,
					["name"] = "Copper Ore",
					["minBid"] = 31120,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1556,
					["quality"] = 1,
				}, -- [181]
				{
					["buyoutUnit"] = 1524,
					["seller"] = "Zzbank",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3049,
					["name"] = "Copper Ore",
					["minBid"] = 3049,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1524,
					["quality"] = 1,
				}, -- [182]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [183]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [184]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [185]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [186]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [187]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 5,
					["buyout"] = 24995,
					["name"] = "Copper Ore",
					["minBid"] = 24995,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [188]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [189]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [190]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [191]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [192]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [193]
				{
					["buyoutUnit"] = 81818,
					["seller"] = "Snaffel",
					["bidAmount"] = 0,
					["count"] = 11,
					["buyout"] = 900000,
					["name"] = "Copper Ore",
					["minBid"] = 700100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 63645,
					["quality"] = 1,
				}, -- [194]
				{
					["buyoutUnit"] = 1646,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 32920,
					["name"] = "Copper Ore",
					["minBid"] = 32920,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1646,
					["quality"] = 1,
				}, -- [195]
				{
					["buyoutUnit"] = 30000,
					["seller"] = "Sostenadaura",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 600000,
					["name"] = "Copper Ore",
					["minBid"] = 580000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 29000,
					["quality"] = 1,
				}, -- [196]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [197]
				{
					["buyoutUnit"] = 30000,
					["seller"] = "Sostenadaura",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 600000,
					["name"] = "Copper Ore",
					["minBid"] = 580000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 29000,
					["quality"] = 1,
				}, -- [198]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [199]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [200]
				{
					["buyoutUnit"] = 25000,
					["seller"] = "Sostenadaura",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 500000,
					["name"] = "Copper Ore",
					["minBid"] = 402000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 20100,
					["quality"] = 1,
				}, -- [201]
				{
					["buyoutUnit"] = 1494,
					["seller"] = "Moneybaggs",
					["bidAmount"] = 0,
					["count"] = 9,
					["buyout"] = 13446,
					["name"] = "Copper Ore",
					["minBid"] = 12762,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1418,
					["quality"] = 1,
				}, -- [202]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [203]
				{
					["buyoutUnit"] = 23020,
					["seller"] = "Jellybear",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 460400,
					["name"] = "Copper Ore",
					["minBid"] = 441600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 22080,
					["quality"] = 1,
				}, -- [204]
				{
					["buyoutUnit"] = 23020,
					["seller"] = "Jellybear",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 460400,
					["name"] = "Copper Ore",
					["minBid"] = 441600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 22080,
					["quality"] = 1,
				}, -- [205]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [206]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [207]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [208]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [209]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [210]
				{
					["buyoutUnit"] = 1760,
					["seller"] = "Hebanks",
					["bidAmount"] = 0,
					["count"] = 8,
					["buyout"] = 14080,
					["name"] = "Copper Ore",
					["minBid"] = 14080,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1760,
					["quality"] = 1,
				}, -- [211]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [212]
				{
					["buyoutUnit"] = 10690,
					["seller"] = "Iightly",
					["bidAmount"] = 0,
					["count"] = 16,
					["buyout"] = 171040,
					["name"] = "Copper Ore",
					["minBid"] = 160000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 10000,
					["quality"] = 1,
				}, -- [213]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [214]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anlr",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [215]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anqs",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [216]
				{
					["buyoutUnit"] = 10000,
					["seller"] = "Sostenadaura",
					["bidAmount"] = 0,
					["count"] = 11,
					["buyout"] = 110000,
					["name"] = "Copper Ore",
					["minBid"] = 108900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 9900,
					["quality"] = 1,
				}, -- [217]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [218]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anqs",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [219]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [220]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [221]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [222]
				{
					["buyoutUnit"] = 6110,
					["seller"] = "Anqs",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 122200,
					["name"] = "Copper Ore",
					["minBid"] = 120100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 6005,
					["quality"] = 1,
				}, -- [223]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [224]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [225]
				{
					["buyoutUnit"] = 1536,
					["seller"] = "Fessacchiona",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30720,
					["name"] = "Copper Ore",
					["minBid"] = 30720,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1536,
					["quality"] = 1,
				}, -- [226]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [227]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [228]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [229]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [230]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [231]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [232]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [233]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [234]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [235]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Furrythead",
					["bidAmount"] = 1389,
					["count"] = 12,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 1200,
					["minIncrement"] = 69,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [236]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [237]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [238]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [239]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [240]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [241]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [242]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [243]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [244]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [245]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [246]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [247]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [248]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [249]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [250]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [251]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [252]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [253]
				{
					["buyoutUnit"] = 23020,
					["seller"] = "Jellybear",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 460400,
					["name"] = "Copper Ore",
					["minBid"] = 441600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 22080,
					["quality"] = 1,
				}, -- [254]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [255]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [256]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Machor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [257]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [258]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [259]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [260]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [261]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 12,
					["buyout"] = 59988,
					["name"] = "Copper Ore",
					["minBid"] = 59988,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [262]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [263]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [264]
				{
					["buyoutUnit"] = 1515,
					["seller"] = "Firedragon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30300,
					["name"] = "Copper Ore",
					["minBid"] = 30100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1505,
					["quality"] = 1,
				}, -- [265]
				{
					["buyoutUnit"] = 1581,
					["seller"] = "Zonereaper",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1581,
					["name"] = "Copper Ore",
					["minBid"] = 1501,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1501,
					["quality"] = 1,
				}, -- [266]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [267]
				{
					["buyoutUnit"] = 1750,
					["seller"] = "Icedragon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 35000,
					["name"] = "Copper Ore",
					["minBid"] = 34900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1745,
					["quality"] = 1,
				}, -- [268]
				{
					["buyoutUnit"] = 1499,
					["seller"] = "Bankerbob",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 14990,
					["name"] = "Copper Ore",
					["minBid"] = 14990,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1499,
					["quality"] = 1,
				}, -- [269]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Machor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [270]
				{
					["buyoutUnit"] = 1442,
					["seller"] = "Hacon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 28850,
					["name"] = "Copper Ore",
					["minBid"] = 28850,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1442,
					["quality"] = 1,
				}, -- [271]
				{
					["buyoutUnit"] = 1556,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 31120,
					["name"] = "Copper Ore",
					["minBid"] = 31120,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1556,
					["quality"] = 1,
				}, -- [272]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [273]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [274]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [275]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Machor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [276]
				{
					["buyoutUnit"] = 1537,
					["seller"] = "Gallstaff",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30750,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [277]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [278]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [279]
				{
					["buyoutUnit"] = 1750,
					["seller"] = "Icedragon",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 35000,
					["name"] = "Copper Ore",
					["minBid"] = 34900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1745,
					["quality"] = 1,
				}, -- [280]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [281]
				{
					["buyoutUnit"] = 1536,
					["seller"] = "Fessacchiona",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30720,
					["name"] = "Copper Ore",
					["minBid"] = 30720,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1536,
					["quality"] = 1,
				}, -- [282]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [283]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [284]
				{
					["buyoutUnit"] = 1760,
					["seller"] = "Hebanks",
					["bidAmount"] = 0,
					["count"] = 17,
					["buyout"] = 29920,
					["name"] = "Copper Ore",
					["minBid"] = 29920,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1760,
					["quality"] = 1,
				}, -- [285]
				{
					["buyoutUnit"] = 1556,
					["seller"] = "Bankofret",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 31120,
					["name"] = "Copper Ore",
					["minBid"] = 31120,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1556,
					["quality"] = 1,
				}, -- [286]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [287]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [288]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [289]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [290]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [291]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [292]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [293]
				{
					["buyoutUnit"] = 3400,
					["seller"] = "Didge",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 68000,
					["name"] = "Copper Ore",
					["minBid"] = 63000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3150,
					["quality"] = 1,
				}, -- [294]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Machor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 22000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1100,
					["quality"] = 1,
				}, -- [295]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [296]
				{
					["buyoutUnit"] = 3300,
					["seller"] = "Dikinbaus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 66000,
					["name"] = "Copper Ore",
					["minBid"] = 61000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3050,
					["quality"] = 1,
				}, -- [297]
				{
					["buyoutUnit"] = 2500,
					["seller"] = "Ohotnik",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 50000,
					["name"] = "Copper Ore",
					["minBid"] = 40100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2005,
					["quality"] = 1,
				}, -- [298]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [299]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [300]
				{
					["buyoutUnit"] = 1389,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 13890,
					["name"] = "Copper Ore",
					["minBid"] = 13180,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1318,
					["quality"] = 1,
				}, -- [301]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [302]
				{
					["buyoutUnit"] = 1536,
					["seller"] = "Fessacchiona",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30720,
					["name"] = "Copper Ore",
					["minBid"] = 30720,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1536,
					["quality"] = 1,
				}, -- [303]
				{
					["buyoutUnit"] = 1640,
					["seller"] = "Lianshou",
					["bidAmount"] = 0,
					["count"] = 6,
					["buyout"] = 9840,
					["name"] = "Copper Ore",
					["minBid"] = 9330,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1555,
					["quality"] = 1,
				}, -- [304]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [305]
				{
					["buyoutUnit"] = 1444,
					["seller"] = "Mumanas",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1444,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [306]
				{
					["buyoutUnit"] = 1499,
					["seller"] = "Bankerbob",
					["bidAmount"] = 0,
					["count"] = 5,
					["buyout"] = 7495,
					["name"] = "Copper Ore",
					["minBid"] = 7495,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1499,
					["quality"] = 1,
				}, -- [307]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [308]
				{
					["buyoutUnit"] = 1469,
					["seller"] = "Kybar",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1469,
					["name"] = "Copper Ore",
					["minBid"] = 1469,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1469,
					["quality"] = 1,
				}, -- [309]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Erdeksw",
					["bidAmount"] = 100,
					["count"] = 1,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [310]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [311]
				{
					["buyoutUnit"] = 1640,
					["seller"] = "Ladutta",
					["bidAmount"] = 0,
					["count"] = 13,
					["buyout"] = 21320,
					["name"] = "Copper Ore",
					["minBid"] = 20215,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1555,
					["quality"] = 1,
				}, -- [312]
				{
					["buyoutUnit"] = 1400,
					["seller"] = "Rukard",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1400,
					["name"] = "Copper Ore",
					["minBid"] = 1400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1400,
					["quality"] = 1,
				}, -- [313]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [314]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Machor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [315]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [316]
				{
					["buyoutUnit"] = 1500,
					["seller"] = "Machor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [317]
				{
					["buyoutUnit"] = 1535,
					["seller"] = "Kolossale",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 30700,
					["name"] = "Copper Ore",
					["minBid"] = 29100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1455,
					["quality"] = 1,
				}, -- [318]
				{
					["buyoutUnit"] = 1520,
					["seller"] = "Wiggelz",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3040,
					["name"] = "Copper Ore",
					["minBid"] = 2880,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1440,
					["quality"] = 1,
				}, -- [319]
			},
		},
	},
}