
AHScannerDB = {
	["Bronzebeard - Warcraft Reborn"] = {
		["Copper Ore"] = {
			["items"] = {
				{
					["buyoutUnit"] = 1990,
					["seller"] = "Chubaka",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39800,
					["name"] = "Copper Ore",
					["minBid"] = 39700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1985,
					["quality"] = 1,
				}, -- [1]
				{
					["buyoutUnit"] = 19800,
					["seller"] = "Lolotaa",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 19800,
					["name"] = "Copper Ore",
					["minBid"] = 18700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 18700,
					["quality"] = 1,
				}, -- [2]
				{
					["buyoutUnit"] = 2300,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 46000,
					["name"] = "Copper Ore",
					["minBid"] = 42000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2100,
					["quality"] = 1,
				}, -- [3]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [4]
				{
					["buyoutUnit"] = 2300,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 46000,
					["name"] = "Copper Ore",
					["minBid"] = 42000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2100,
					["quality"] = 1,
				}, -- [5]
				{
					["buyoutUnit"] = 10000,
					["seller"] = "Palmam",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 100000,
					["name"] = "Copper Ore",
					["minBid"] = 50000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 5000,
					["quality"] = 1,
				}, -- [6]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Happyxhunter",
					["bidAmount"] = 100,
					["count"] = 5,
					["buyout"] = 10000,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 20,
					["quality"] = 1,
				}, -- [7]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [8]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [9]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [10]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [11]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [12]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [13]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [14]
				{
					["buyoutUnit"] = 1740,
					["seller"] = "Degrading",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 34800,
					["name"] = "Copper Ore",
					["minBid"] = 33000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1650,
					["quality"] = 1,
				}, -- [15]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [16]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Happyxhunter",
					["bidAmount"] = 100,
					["count"] = 5,
					["buyout"] = 10000,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 20,
					["quality"] = 1,
				}, -- [17]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [18]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [19]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [20]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [21]
				{
					["buyoutUnit"] = 1720,
					["seller"] = "Minatsuky",
					["bidAmount"] = 0,
					["count"] = 9,
					["buyout"] = 15480,
					["name"] = "Copper Ore",
					["minBid"] = 14670,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1630,
					["quality"] = 1,
				}, -- [22]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [23]
				{
					["buyoutUnit"] = 1710,
					["seller"] = "Grimmly",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 34200,
					["name"] = "Copper Ore",
					["minBid"] = 32400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1620,
					["quality"] = 1,
				}, -- [24]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [25]
				{
					["buyoutUnit"] = 4900,
					["seller"] = "Mangalche",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 98000,
					["name"] = "Copper Ore",
					["minBid"] = 92000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4600,
					["quality"] = 1,
				}, -- [26]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Happyxhunter",
					["bidAmount"] = 100,
					["count"] = 5,
					["buyout"] = 10000,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 20,
					["quality"] = 1,
				}, -- [27]
				{
					["buyoutUnit"] = 1999,
					["seller"] = "Bankmishap",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39999,
					["name"] = "Copper Ore",
					["minBid"] = 39999,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1999,
					["quality"] = 1,
				}, -- [28]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [29]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 5,
					["buyout"] = 24995,
					["name"] = "Copper Ore",
					["minBid"] = 24995,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [30]
				{
					["buyoutUnit"] = 1705,
					["seller"] = "Bankerbub",
					["bidAmount"] = 0,
					["count"] = 3,
					["buyout"] = 5115,
					["name"] = "Copper Ore",
					["minBid"] = 4845,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1615,
					["quality"] = 1,
				}, -- [31]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [32]
				{
					["buyoutUnit"] = 2400,
					["seller"] = "Outland",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 48000,
					["name"] = "Copper Ore",
					["minBid"] = 44000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2200,
					["quality"] = 1,
				}, -- [33]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [34]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [35]
				{
					["buyoutUnit"] = 1730,
					["seller"] = "Houndstooth",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3460,
					["name"] = "Copper Ore",
					["minBid"] = 3280,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1640,
					["quality"] = 1,
				}, -- [36]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [37]
				{
					["buyoutUnit"] = 10000,
					["seller"] = "Furrythead",
					["bidAmount"] = 1100,
					["count"] = 11,
					["buyout"] = 110000,
					["name"] = "Copper Ore",
					["minBid"] = 1100,
					["minIncrement"] = 55,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [38]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [39]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [40]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Otterpus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 40000,
					["name"] = "Copper Ore",
					["minBid"] = 37900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1895,
					["quality"] = 1,
				}, -- [41]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Happyxhunter",
					["bidAmount"] = 100,
					["count"] = 5,
					["buyout"] = 10000,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 20,
					["quality"] = 1,
				}, -- [42]
				{
					["buyoutUnit"] = 1975,
					["seller"] = "Zorth",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39500,
					["name"] = "Copper Ore",
					["minBid"] = 39500,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1975,
					["quality"] = 1,
				}, -- [43]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [44]
				{
					["buyoutUnit"] = 1705,
					["seller"] = "Bankerbub",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 34100,
					["name"] = "Copper Ore",
					["minBid"] = 32300,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1615,
					["quality"] = 1,
				}, -- [45]
				{
					["buyoutUnit"] = 1875,
					["seller"] = "Lockmind",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1875,
					["name"] = "Copper Ore",
					["minBid"] = 1000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1000,
					["quality"] = 1,
				}, -- [46]
				{
					["buyoutUnit"] = 1740,
					["seller"] = "Degrading",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 34800,
					["name"] = "Copper Ore",
					["minBid"] = 33000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1650,
					["quality"] = 1,
				}, -- [47]
				{
					["buyoutUnit"] = 2500,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 50000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [48]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Happyxhunter",
					["bidAmount"] = 100,
					["count"] = 5,
					["buyout"] = 10000,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 20,
					["quality"] = 1,
				}, -- [49]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [50]
				{
					["buyoutUnit"] = 1990,
					["seller"] = "Chubaka",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39800,
					["name"] = "Copper Ore",
					["minBid"] = 39700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1985,
					["quality"] = 1,
				}, -- [51]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [52]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [53]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [54]
				{
					["buyoutUnit"] = 5000,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 100000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [55]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [56]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [57]
				{
					["buyoutUnit"] = 1725,
					["seller"] = "Sangtana",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1725,
					["name"] = "Copper Ore",
					["minBid"] = 1635,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1635,
					["quality"] = 1,
				}, -- [58]
				{
					["buyoutUnit"] = 1995,
					["seller"] = "Althor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39900,
					["name"] = "Copper Ore",
					["minBid"] = 37800,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1890,
					["quality"] = 1,
				}, -- [59]
				{
					["buyoutUnit"] = 4900,
					["seller"] = "Mangalche",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 98000,
					["name"] = "Copper Ore",
					["minBid"] = 92000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4600,
					["quality"] = 1,
				}, -- [60]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [61]
				{
					["buyoutUnit"] = 1999,
					["seller"] = "Bankmishap",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39999,
					["name"] = "Copper Ore",
					["minBid"] = 39999,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1999,
					["quality"] = 1,
				}, -- [62]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [63]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [64]
				{
					["buyoutUnit"] = 2300,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 46000,
					["name"] = "Copper Ore",
					["minBid"] = 42000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2100,
					["quality"] = 1,
				}, -- [65]
				{
					["buyoutUnit"] = 20100,
					["seller"] = "Prle",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 402000,
					["name"] = "Copper Ore",
					["minBid"] = 402000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 20100,
					["quality"] = 1,
				}, -- [66]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [67]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [68]
				{
					["buyoutUnit"] = 15055,
					["seller"] = "Loveheart",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 150550,
					["name"] = "Copper Ore",
					["minBid"] = 150550,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 15055,
					["quality"] = 1,
				}, -- [69]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [70]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [71]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [72]
				{
					["buyoutUnit"] = 5000,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 100000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [73]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [74]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [75]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [76]
				{
					["buyoutUnit"] = 5000,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 100000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [77]
				{
					["buyoutUnit"] = 5000,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 100000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [78]
				{
					["buyoutUnit"] = 5000,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 100000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [79]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [80]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [81]
				{
					["buyoutUnit"] = 5000,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 100000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [82]
				{
					["buyoutUnit"] = 5000,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 100000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [83]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [84]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [85]
				{
					["buyoutUnit"] = 1895,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 4,
					["buyout"] = 7580,
					["name"] = "Copper Ore",
					["minBid"] = 7180,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1795,
					["quality"] = 1,
				}, -- [86]
				{
					["buyoutUnit"] = 5500,
					["seller"] = "Mycelia",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 55000,
					["name"] = "Copper Ore",
					["minBid"] = 55000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 5500,
					["quality"] = 1,
				}, -- [87]
				{
					["buyoutUnit"] = 7500,
					["seller"] = "Draxas",
					["bidAmount"] = 600,
					["count"] = 6,
					["buyout"] = 45000,
					["name"] = "Copper Ore",
					["minBid"] = 600,
					["minIncrement"] = 30,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [88]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [89]
				{
					["buyoutUnit"] = 1689,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 16890,
					["name"] = "Copper Ore",
					["minBid"] = 16030,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1603,
					["quality"] = 1,
				}, -- [90]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [91]
				{
					["buyoutUnit"] = 5000,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 100000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [92]
				{
					["buyoutUnit"] = 1989,
					["seller"] = "Burnsalot",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1989,
					["name"] = "Copper Ore",
					["minBid"] = 1989,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1989,
					["quality"] = 1,
				}, -- [93]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [94]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [95]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [96]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [97]
				{
					["buyoutUnit"] = 2300,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 46000,
					["name"] = "Copper Ore",
					["minBid"] = 42000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2100,
					["quality"] = 1,
				}, -- [98]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [99]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [100]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [101]
				{
					["buyoutUnit"] = 4900,
					["seller"] = "Mangalche",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 98000,
					["name"] = "Copper Ore",
					["minBid"] = 92000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4600,
					["quality"] = 1,
				}, -- [102]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [103]
				{
					["buyoutUnit"] = 1715,
					["seller"] = "Spanko",
					["bidAmount"] = 0,
					["count"] = 8,
					["buyout"] = 13720,
					["name"] = "Copper Ore",
					["minBid"] = 13000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1625,
					["quality"] = 1,
				}, -- [104]
				{
					["buyoutUnit"] = 2400,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 3,
					["buyout"] = 7200,
					["name"] = "Copper Ore",
					["minBid"] = 6600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2200,
					["quality"] = 1,
				}, -- [105]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Adram",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 200,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [106]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [107]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 12,
					["buyout"] = 59988,
					["name"] = "Copper Ore",
					["minBid"] = 59988,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [108]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [109]
				{
					["buyoutUnit"] = 1710,
					["seller"] = "Grimmly",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3420,
					["name"] = "Copper Ore",
					["minBid"] = 3240,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1620,
					["quality"] = 1,
				}, -- [110]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [111]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [112]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [113]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [114]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [115]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [116]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Happyxhunter",
					["bidAmount"] = 100,
					["count"] = 5,
					["buyout"] = 10000,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 20,
					["quality"] = 1,
				}, -- [117]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [118]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [119]
				{
					["buyoutUnit"] = 1750,
					["seller"] = "Babeavenger",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3500,
					["name"] = "Copper Ore",
					["minBid"] = 3500,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1750,
					["quality"] = 1,
				}, -- [120]
				{
					["buyoutUnit"] = 1689,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 16890,
					["name"] = "Copper Ore",
					["minBid"] = 16030,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1603,
					["quality"] = 1,
				}, -- [121]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [122]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [123]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [124]
				{
					["buyoutUnit"] = 2500,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 50000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [125]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [126]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [127]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Happyxhunter",
					["bidAmount"] = 100,
					["count"] = 5,
					["buyout"] = 10000,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 20,
					["quality"] = 1,
				}, -- [128]
				{
					["buyoutUnit"] = 10000,
					["seller"] = "Chubaka",
					["bidAmount"] = 0,
					["count"] = 12,
					["buyout"] = 120000,
					["name"] = "Copper Ore",
					["minBid"] = 118800,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 9900,
					["quality"] = 1,
				}, -- [129]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [130]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Pilarica",
					["bidAmount"] = 346,
					["count"] = 3,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 300,
					["minIncrement"] = 17,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [131]
				{
					["buyoutUnit"] = 1689,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 16890,
					["name"] = "Copper Ore",
					["minBid"] = 16030,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1603,
					["quality"] = 1,
				}, -- [132]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [133]
				{
					["buyoutUnit"] = 4900,
					["seller"] = "Mangalche",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 98000,
					["name"] = "Copper Ore",
					["minBid"] = 92000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4600,
					["quality"] = 1,
				}, -- [134]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [135]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [136]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [137]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Bral",
					["bidAmount"] = 4067,
					["count"] = 17,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 1700,
					["minIncrement"] = 203,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [138]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [139]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 4,
					["buyout"] = 17995,
					["name"] = "Copper Ore",
					["minBid"] = 17095,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [140]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [141]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [142]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [143]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [144]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [145]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [146]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [147]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [148]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [149]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 5,
					["buyout"] = 24995,
					["name"] = "Copper Ore",
					["minBid"] = 24995,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [150]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [151]
				{
					["buyoutUnit"] = 2300,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 46000,
					["name"] = "Copper Ore",
					["minBid"] = 42000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2100,
					["quality"] = 1,
				}, -- [152]
				{
					["buyoutUnit"] = 2400,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 8,
					["buyout"] = 19200,
					["name"] = "Copper Ore",
					["minBid"] = 17600,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2200,
					["quality"] = 1,
				}, -- [153]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [154]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [155]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [156]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [157]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [158]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [159]
				{
					["buyoutUnit"] = 3500,
					["seller"] = "Gitguditryin",
					["bidAmount"] = 0,
					["count"] = 6,
					["buyout"] = 21000,
					["name"] = "Copper Ore",
					["minBid"] = 20400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 3400,
					["quality"] = 1,
				}, -- [160]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [161]
				{
					["buyoutUnit"] = 1689,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 16890,
					["name"] = "Copper Ore",
					["minBid"] = 16030,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1603,
					["quality"] = 1,
				}, -- [162]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [163]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [164]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Pilarica",
					["bidAmount"] = 4001,
					["count"] = 11,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 1100,
					["minIncrement"] = 200,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [165]
				{
					["buyoutUnit"] = 20000,
					["seller"] = "Furrythead",
					["bidAmount"] = 0,
					["count"] = 16,
					["buyout"] = 320000,
					["name"] = "Copper Ore",
					["minBid"] = 320000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 20000,
					["quality"] = 1,
				}, -- [166]
				{
					["buyoutUnit"] = 2300,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 46000,
					["name"] = "Copper Ore",
					["minBid"] = 42000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2100,
					["quality"] = 1,
				}, -- [167]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [168]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [169]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [170]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [171]
				{
					["buyoutUnit"] = 1995,
					["seller"] = "Althor",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39900,
					["name"] = "Copper Ore",
					["minBid"] = 37800,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1890,
					["quality"] = 1,
				}, -- [172]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [173]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [174]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [175]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [176]
				{
					["buyoutUnit"] = 5500,
					["seller"] = "Mycelia",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 5500,
					["name"] = "Copper Ore",
					["minBid"] = 5500,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 5500,
					["quality"] = 1,
				}, -- [177]
				{
					["buyoutUnit"] = 1990,
					["seller"] = "Chubaka",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39800,
					["name"] = "Copper Ore",
					["minBid"] = 39700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1985,
					["quality"] = 1,
				}, -- [178]
				{
					["buyoutUnit"] = 1990,
					["seller"] = "Chubaka",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39800,
					["name"] = "Copper Ore",
					["minBid"] = 39700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1985,
					["quality"] = 1,
				}, -- [179]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [180]
				{
					["buyoutUnit"] = 2300,
					["seller"] = "Trollenger",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 46000,
					["name"] = "Copper Ore",
					["minBid"] = 42000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2100,
					["quality"] = 1,
				}, -- [181]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [182]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [183]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [184]
				{
					["buyoutUnit"] = 2500,
					["seller"] = "Minao",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 50000,
					["name"] = "Copper Ore",
					["minBid"] = 20100,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1005,
					["quality"] = 1,
				}, -- [185]
				{
					["buyoutUnit"] = 1745,
					["seller"] = "Zeuta",
					["bidAmount"] = 0,
					["count"] = 2,
					["buyout"] = 3490,
					["name"] = "Copper Ore",
					["minBid"] = 3305,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1652,
					["quality"] = 1,
				}, -- [186]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Otterpus",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 40000,
					["name"] = "Copper Ore",
					["minBid"] = 37900,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1895,
					["quality"] = 1,
				}, -- [187]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [188]
				{
					["buyoutUnit"] = 1700,
					["seller"] = "Wylliam",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1700,
					["name"] = "Copper Ore",
					["minBid"] = 1610,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1610,
					["quality"] = 1,
				}, -- [189]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [190]
				{
					["buyoutUnit"] = 1735,
					["seller"] = "Leviticous",
					["bidAmount"] = 0,
					["count"] = 3,
					["buyout"] = 5205,
					["name"] = "Copper Ore",
					["minBid"] = 4935,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1645,
					["quality"] = 1,
				}, -- [191]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [192]
				{
					["buyoutUnit"] = 1900,
					["seller"] = "Levus",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1900,
					["name"] = "Copper Ore",
					["minBid"] = 1800,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1800,
					["quality"] = 1,
				}, -- [193]
				{
					["buyoutUnit"] = 1740,
					["seller"] = "Degrading",
					["bidAmount"] = 0,
					["count"] = 13,
					["buyout"] = 22620,
					["name"] = "Copper Ore",
					["minBid"] = 21450,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1650,
					["quality"] = 1,
				}, -- [194]
				{
					["buyoutUnit"] = 2400,
					["seller"] = "Outland",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 48000,
					["name"] = "Copper Ore",
					["minBid"] = 44000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 2200,
					["quality"] = 1,
				}, -- [195]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [196]
				{
					["buyoutUnit"] = 1689,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 16890,
					["name"] = "Copper Ore",
					["minBid"] = 16030,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1603,
					["quality"] = 1,
				}, -- [197]
				{
					["buyoutUnit"] = 4900,
					["seller"] = "Mangalche",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 98000,
					["name"] = "Copper Ore",
					["minBid"] = 92000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4600,
					["quality"] = 1,
				}, -- [198]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [199]
				{
					["buyoutUnit"] = 4999,
					["seller"] = "Craftsanity",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 99980,
					["name"] = "Copper Ore",
					["minBid"] = 99980,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4999,
					["quality"] = 1,
				}, -- [200]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [201]
				{
					["buyoutUnit"] = 1990,
					["seller"] = "Chubaka",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39800,
					["name"] = "Copper Ore",
					["minBid"] = 39700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1985,
					["quality"] = 1,
				}, -- [202]
				{
					["buyoutUnit"] = 2000,
					["seller"] = "Happyxhunter",
					["bidAmount"] = 100,
					["count"] = 5,
					["buyout"] = 10000,
					["name"] = "Copper Ore",
					["minBid"] = 100,
					["minIncrement"] = 5,
					["level"] = 0,
					["minBidUnit"] = 20,
					["quality"] = 1,
				}, -- [203]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [204]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [205]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [206]
				{
					["buyoutUnit"] = 1690,
					["seller"] = "Khamel",
					["bidAmount"] = 0,
					["count"] = 9,
					["buyout"] = 15210,
					["name"] = "Copper Ore",
					["minBid"] = 14400,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1600,
					["quality"] = 1,
				}, -- [207]
				{
					["buyoutUnit"] = 10000,
					["seller"] = "Nimuroddo",
					["bidAmount"] = 0,
					["count"] = 3,
					["buyout"] = 30000,
					["name"] = "Copper Ore",
					["minBid"] = 15000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 5000,
					["quality"] = 1,
				}, -- [208]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [209]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [210]
				{
					["buyoutUnit"] = 1740,
					["seller"] = "Degrading",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 34800,
					["name"] = "Copper Ore",
					["minBid"] = 33000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1650,
					["quality"] = 1,
				}, -- [211]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [212]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [213]
				{
					["buyoutUnit"] = 4498,
					["seller"] = "Umrokupajuga",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 4498,
					["name"] = "Copper Ore",
					["minBid"] = 4273,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4273,
					["quality"] = 1,
				}, -- [214]
				{
					["buyoutUnit"] = 4900,
					["seller"] = "Mangalche",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 98000,
					["name"] = "Copper Ore",
					["minBid"] = 92000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 4600,
					["quality"] = 1,
				}, -- [215]
				{
					["buyoutUnit"] = 1990,
					["seller"] = "Chubaka",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39800,
					["name"] = "Copper Ore",
					["minBid"] = 39700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1985,
					["quality"] = 1,
				}, -- [216]
				{
					["buyoutUnit"] = 1689,
					["seller"] = "Zuzz",
					["bidAmount"] = 0,
					["count"] = 10,
					["buyout"] = 16890,
					["name"] = "Copper Ore",
					["minBid"] = 16030,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1603,
					["quality"] = 1,
				}, -- [217]
				{
					["buyoutUnit"] = 1695,
					["seller"] = "Genocidexd",
					["bidAmount"] = 0,
					["count"] = 1,
					["buyout"] = 1695,
					["name"] = "Copper Ore",
					["minBid"] = 1605,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1605,
					["quality"] = 1,
				}, -- [218]
				{
					["buyoutUnit"] = 0,
					["seller"] = "Blammowyn",
					["bidAmount"] = 981,
					["count"] = 7,
					["buyout"] = 0,
					["name"] = "Copper Ore",
					["minBid"] = 700,
					["minIncrement"] = 49,
					["level"] = 0,
					["minBidUnit"] = 100,
					["quality"] = 1,
				}, -- [219]
				{
					["buyoutUnit"] = 1990,
					["seller"] = "Chubaka",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 39800,
					["name"] = "Copper Ore",
					["minBid"] = 39700,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1985,
					["quality"] = 1,
				}, -- [220]
				{
					["buyoutUnit"] = 1740,
					["seller"] = "Degrading",
					["bidAmount"] = 0,
					["count"] = 20,
					["buyout"] = 34800,
					["name"] = "Copper Ore",
					["minBid"] = 33000,
					["minIncrement"] = 0,
					["level"] = 0,
					["minBidUnit"] = 1650,
					["quality"] = 1,
				}, -- [221]
			},
		},
	},
}